### ISSUE TITLE
Hello! When I run the following program according to your prompt, I get an error again, and I want to ask you

### ISSUE THREAD

**Issue by dcy0324** [shariqiqbal2810/maddpg-pytorch#15]
Hello! When I run the following program according to your prompt, the following error occurs again. What is the reason?
python main.py simple_world_comm predator-prey
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    run(config)
  File "main.py", line 52, in run
    config.discrete_action)
  File "main.py", line 26, in make_parallel_env
    return DummyVecEnv([get_env_fn(0)])
  File "/home/dcy/MADDPG/maddpg-pytorch-master/utils/env_wrappers.py", line 99, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/dcy/MADDPG/maddpg-pytorch-master/utils/env_wrappers.py", line 99, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "main.py", line 20, in init_env
    env = make_env(env_id, discrete_action=discrete_action)
  File "/home/dcy/MADDPG/maddpg-pytorch-master/utils/make_env.py", line 47, in make_env
    discrete_action=discrete_action)
TypeError: __init__() got an unexpected keyword argument 'discrete_action'

**Comment by shariqiqbal2810** [comment]
Are you making sure to use my [fork of multiagent-particle-envs](https://github.com/shariqiqbal2810/multiagent-particle-envs)?

This command will still not work though, as `simple-world-comm` requires policies with multiple action outputs (in this case a physical action as well as a communication action), which is not supported by this codebase.
